apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-udp-server
  name: test-udp-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-udp-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-udp-server
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/hallowed-spider-407610/test-repo/udp-server-test-py:73d0438d4ed4536721f4dead40de31fdce93f61e
        name: udp-server-test-py
        resources: {}
status: {}
